baseurl = "https://shadowd.zecure.org"
MetaDataFormat = "yaml"

[markup.goldmark.renderer]
  unsafe= true

[indexes]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "downloads"
    pre = "<i class='fa fa-download'></i>"
    weight = -120
[[menu.main]]
    name = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
[[menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
[[menu.main]]
    name = "documentation"
    pre = "<i class='fa fa-graduation-cap'></i>"
    weight = -90
[[menu.main]]
    name = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -80
[[menu.main]]
    name = "development"
    pre = "<i class='fa fa-cog'></i>"
    weight = -70

[params]
  shadowd-version = '2.2.0'
  foobar = 'boofar'
  shadowd_ui-version = '2.0.6'
  shadowd_php-version = '2.2.0'
  shadowd_perl-version = '2.0.0'
  shadowd_python-version = '3.0.2'
  shadowdctl-version = '2.0.0'